name: Staging Frontend Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env for Next.js build
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ vars.STAGE_NEXT_PUBLIC_API_URL }}" > .env
          echo "NODE_ENV=staging" >> .env

      - name: Allow .env in Docker build
        run: sed -i '/.env/d' .dockerignore || true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.GH_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        env:
          REGISTRY: ${{ secrets.ECR_REGISTRY }}
          REPOSITORY: stage-chatbot-web
        run: |
          docker build --no-cache \
            -f Dockerfile-fe \
            -t $REGISTRY/$REPOSITORY:latest .

          docker push $REGISTRY/$REPOSITORY:latest

      - name: Deploy with Docker Compose
        run: |
          cd /home/ubuntu/actions-runner

          docker compose -p prod -f prod-compose.yaml pull

          docker compose -p prod -f prod-compose.yaml up -d

          docker image prune -f
