name: Staging Frontend Deploy

on:
  push:
    branches:
      - staging-fix

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env for Next.js build
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}" > .env
          echo "NODE_ENV=production" >> .env

      - name: Allow .env in Docker build
        run: sed -i '/.env/d' .dockerignore || true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.GH_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        env:
          REGISTRY: ${{ secrets.ECR_REGISTRY }}
          REPOSITORY: stage-chatbot-web
        run: |
          docker build --no-cache \
            -f Dockerfile-fe \
            -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: stage-chatbot-web.json
          cluster: stage-cluster
          service: stage-chatbot-web-service
          force-new-deployment: true
          wait-for-service-stability: false
